name: Crear Log

on:
  push:

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Crear archivo log
        run: |
          echo "Commit hecho por ${{ github.actor }}" >> log.txt
          echo "Mensaje: ${{ github.event.head_commit.message }}" >> log.txt
          
      # Eliminamos cualquier intento de push